FROM debian:bookworm-slim AS base
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN cp /etc/apt/sources.list.d/debian.sources /tmp/debian.sources.bak && \
    sed -i 's|deb.debian.org/debian|ftp.cn.debian.org/debian|g' /etc/apt/sources.list.d/debian.sources && \
    apt update && \
    apt install -y libicu72 --no-install-recommends && \
    apt clean && \
    rm -rf /var/lib/apt/lists && \
    mv /tmp/debian.sources.bak /etc/apt/sources.list.d/debian.sources

COPY ./ffmpeg/lib/* /usr/lib
