name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install submodules
        run: git submodule init && git submodule update
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      # 编译和发布应用程序
      - name: Build for Linux x64
        run: dotnet publish "./StreamingCaptureBot.Hosting/StreamingCaptureBot.Hosting.csproj" -c Release -r linux-x64 --self-contained -o output/linux-x64

      - name: Build for Windows x64
        run: dotnet publish "./StreamingCaptureBot.Hosting/StreamingCaptureBot.Hosting.csproj" -c Release -r win-x64 --self-contained -o output/win-x64

      - name: Build for Portable (any-x64)
        run: dotnet publish "./StreamingCaptureBot.Hosting/StreamingCaptureBot.Hosting.csproj" -c Release -o output/any-x64

      # 压缩编译结果
      - name: Zip Linux x64
        run: zip -r StreamingCaptureBot_with-runtime_linux-x64.zip output/linux-x64

      - name: Zip Windows x64
        run: zip -r StreamingCaptureBot_with-runtime_win-x64.zip output/win-x64

      - name: Zip Portable (any-x64)
        run: zip -r StreamingCaptureBot_no-runtime_any-x64.zip output/any-x64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            StreamingCaptureBot_with-runtime_linux-x64.zip
            StreamingCaptureBot_with-runtime_win-x64.zip
            StreamingCaptureBot_no-runtime_any-x64.zip

